# Generated by Django 2.2 on 2022-01-12 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0003_db_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='db_project',
            old_name='user_id',
            new_name='user_name',
        ),
    ]
