# Generated by Django 2.2 on 2022-03-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0005_db_apis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_apis',
            name='body_method',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
